// Rebuild albums.json with verified accurate dates
const fs = require('fs');
const db = {};

function add(date, item) {
  if (!db[date]) db[date] = { date, items: [] };
  if (db[date].items.length < 3) db[date].items.push(item);
}

// ========== JANUARY ==========
add('01-14', {id:'bowie-low-1977',name:'Low',nameZh:'低迷',artist:'David Bowie',artistZh:'大卫·鲍伊',releaseDate:'01-14',year:1977,coverImage:'',genres:['Art Rock','Electronic'],language:'english',languageZh:'英语',type:'album',descriptionZh:'鲍伊与Brian Eno合作的柏林三部曲之首。A面为断裂合成器短歌，B面为纯粹氛围音乐。',descriptionEn:'First of Bowie Berlin Trilogy with Eno. Side A: fractured synth-pop. Side B: pure ambient.',storiesZh:'录制时鲍伊深陷可卡因成瘾，搬到柏林逃离洛杉矶。RCA最初拒绝发行——后来成为他最具影响力的作品之一。',storiesEn:'Recorded while Bowie battled cocaine addiction in Berlin exile. RCA refused initially — became one of his most influential works.',links:{}});
add('01-14', {id:'faye-wong-fuzao-1996',name:'浮躁',nameZh:'浮躁',artist:'Faye Wong',artistZh:'王菲',releaseDate:'01-14',year:1996,coverImage:'',genres:['Art Pop','Alternative'],language:'chinese',languageZh:'华语',type:'album',descriptionZh:'王菲最具实验性的专辑，由窦唯制作。大量无词吟唱，同名曲只用「浮躁」二字循环。',descriptionEn:'Faye Wong most experimental album, produced by Dou Wei. Extensive wordless vocals, minimalist lyrics.',storiesZh:'窦唯鼓励王菲抛开商业顾虑做真正想做的音乐。商业成绩虽不如前作，多年后被公认为华语另类经典。',storiesEn:'Dou Wei encouraged Wong to ignore commercial concerns. Less successful initially, now recognized as a Chinese alt-pop milestone.',links:{}});
add('01-14', {id:'kate-bush-hounds-1985',name:'Hounds of Love',nameZh:'爱之犬',artist:'Kate Bush',artistZh:'凯特·布什',releaseDate:'01-14',year:1985,coverImage:'',genres:['Art Pop','Progressive Pop'],language:'english',languageZh:'英语',type:'album',descriptionZh:'凯特·布什第五张专辑。A面精雕流行曲，B面为溺水者幻觉概念组曲。37年后因《怪奇物语》重新登顶全球榜。',descriptionEn:'Kate Bush fifth album. Side A: crafted pop. Side B: concept suite about drowning. Topped charts 37 years later via Stranger Things.',storiesZh:'在自家录音棚独立完成，远离唱片公司干预。《Running Up That Hill》被迫从《A Deal With God》改名。',storiesEn:'Recorded in home studio free from label interference. Forced to rename lead single over religious concerns.',links:{}});

// ========== FEBRUARY ==========
add('02-13', {id:'strokes-is-this-it-2001',name:'Is This It',nameZh:'就这样吗',artist:'The Strokes',artistZh:'鼓击乐队',releaseDate:'02-13',year:2001,coverImage:'',genres:['Indie Rock','Garage Rock'],language:'english',languageZh:'英语',type:'album',descriptionZh:'The Strokes首专掀起车库摇滚复兴。11首短小精悍的歌曲，脏吉他音色定义2000年代独立摇滚美学。',descriptionEn:'The Strokes debut ignited garage rock revival. 11 tight songs with dirty guitar defined 2000s indie rock.',storiesZh:'美国版因911后将涉及警察暴力的《New York City Cops》替换。封面由吉他手女友拍摄。',storiesEn:'US version replaced New York City Cops post-9/11. Cover shot by guitarist girlfriend.',links:{}});
add('02-13', {id:'omnipotent-youth-2012',name:'万能青年旅店',nameZh:'万能青年旅店',artist:'Omnipotent Youth Society',artistZh:'万能青年旅店',releaseDate:'02-13',year:2012,coverImage:'',genres:['Indie Rock','Chinese Rock'],language:'chinese',languageZh:'华语',type:'album',descriptionZh:'河北乐队首专，诗意歌词与独特小号编配将小镇日常升华为史诗。《杀死那个石家庄人》成中国独立音乐国歌。',descriptionEn:'Hebei band debut. Poetic lyrics with brass arrangements elevate small-town life to epic.',storiesZh:'打磨十年，主脑董亚千在石家庄过着隐居生活，拒绝商业演出。纯靠口碑从地下扩散到主流。',storiesEn:'A decade in the making. Frontman lives reclusive life in Shijiazhuang, refusing commercial gigs.',links:{}});
add('02-13', {id:'tracy-chapman-debut-1988',name:'Tracy Chapman',nameZh:'特蕾西·查普曼',artist:'Tracy Chapman',artistZh:'特蕾西·查普曼',releaseDate:'02-13',year:1988,coverImage:'',genres:['Folk','Singer-Songwriter'],language:'english',languageZh:'英语',type:'album',descriptionZh:'在合成器盛行的80年代末，纯吉他民谣专辑以朴素力量震撼世界。《Fast Car》讲述逃离贫穷循环的故事。',descriptionEn:'Pure guitar folk stunned the synth-heavy late 80s. Fast Car tells story of escaping poverty cycle.',storiesZh:'1989年格莱美上不知名的黑人女性抱着木吉他面对数亿观众，成为格莱美史上最难忘时刻之一。',storiesEn:'Unknown young Black woman with acoustic guitar before billions at 1989 Grammys — one of its most unforgettable moments.',links:{}});

add('02-24', {id:'led-zep-physical-1975',name:'Physical Graffiti',nameZh:'物理涂鸦',artist:'Led Zeppelin',artistZh:'齐柏林飞艇',releaseDate:'02-24',year:1975,coverImage:'',genres:['Hard Rock','Blues Rock'],language:'english',languageZh:'英语',type:'album',descriptionZh:'齐柏林飞艇唯一双专辑，从《Kashmir》到《Bron-Yr-Aur》展现惊人风格跨度。',descriptionEn:'Led Zeppelin only double album. From Kashmir to Bron-Yr-Aur, astonishing stylistic range.',storiesZh:'封面用纽约东村真实公寓楼，模切工艺实现「开窗」效果。一半素材来自前几张专辑未收曲目。',storiesEn:'Cover features real NYC building with die-cut windows. Half material from earlier outtakes.',links:{}});
add('02-24', {id:'cui-jian-new-march-1989',name:'新长征路上的摇滚',nameZh:'新长征路上的摇滚',artist:'Cui Jian',artistZh:'崔健',releaseDate:'02-24',year:1989,coverImage:'',genres:['Rock','Chinese Rock'],language:'chinese',languageZh:'华语',type:'album',descriptionZh:'中国摇滚开山之作。《一无所有》《花房姑娘》成经典。崔健身穿军装蒙眼封面成最标志性符号。',descriptionEn:'The founding work of Chinese rock. Blindfolded military uniform cover became iconic symbol.',storiesZh:'1986年崔健在北京工人体育馆首唱《一无所有》，台下先是震惊后爆发出欢呼——这天被称为中国摇滚元年。',storiesEn:'1986: Cui premiered Nothing to My Name at Beijing Workers Gymnasium. Audience stunned, then erupted — Year Zero of Chinese rock.',links:{}});
add('02-24', {id:'talking-heads-remain-1980',name:'Remain in Light',nameZh:'留在光中',artist:'Talking Heads',artistZh:'传声头像',releaseDate:'02-24',year:1980,coverImage:'',genres:['New Wave','Afrobeat'],language:'english',languageZh:'英语',type:'album',descriptionZh:'拥抱非洲节奏与复调音乐，大量循环和多层打击乐。《Born Under Punches》至今令人震撼。',descriptionEn:'Embraced African polyrhythms with extensive looping. Born Under Punches still stuns.',storiesZh:'乐队即兴演奏，Eno录音循环处理，Byrne在此基础上创作旋律——「先编曲后写歌」极为罕见。',storiesEn:'Band improvised, Eno looped, Byrne wrote on top — reverse approach creating unprecedented sound.',links:{}});

// ========== MARCH ==========
add('03-01', {id:'pink-floyd-dark-side-1973',name:'The Dark Side of the Moon',nameZh:'月之暗面',artist:'Pink Floyd',artistZh:'平克·弗洛伊德',releaseDate:'03-01',year:1973,coverImage:'',genres:['Progressive Rock'],language:'english',languageZh:'英语',type:'album',descriptionZh:'音乐史销量最高专辑之一，Billboard在榜937周纪录至今未破。心跳声、收银机声贯穿全专。',descriptionEn:'One of best-selling albums ever. 937 weeks on Billboard — unbroken record. Heartbeats and cash registers throughout.',storiesZh:'女歌手Clare Torry在《The Great Gig in the Sky》中的无词呐喊即兴完成，录后担心搞砸——成为摇滚史最动人声乐之一。',storiesEn:'Clare Torry improvised wordless vocals on Great Gig — terrified she ruined it. Became one of rock most moving performances.',links:{}});
add('03-01', {id:'jolin-tsai-muse-2012',name:'Muse',nameZh:'Muse',artist:'Jolin Tsai',artistZh:'蔡依林',releaseDate:'03-01',year:2012,coverImage:'',genres:['Mandopop','Dance Pop'],language:'chinese',languageZh:'华语',type:'album',descriptionZh:'蔡依林第12张专辑，融合电子舞曲与实验元素，展现华语天后不断突破的决心。',descriptionEn:'Jolin 12th album blends electronic dance with experimental elements, showing diva determination to evolve.',storiesZh:'为这张专辑练习钢管舞和芭蕾长达半年，身上多处淤青。从被质疑到最具冒险精神天后。',storiesEn:'Trained pole dancing and ballet for six months, covered in bruises. From doubted idol to most adventurous diva.',links:{}});
add('03-01', {id:'miles-davis-kind-of-blue-1959',name:'Kind of Blue',nameZh:'一种蓝色',artist:'Miles Davis',artistZh:'迈尔斯·戴维斯',releaseDate:'03-01',year:1959,coverImage:'',genres:['Jazz','Modal Jazz'],language:'other',languageZh:'纯音乐',type:'album',descriptionZh:'爵士史最伟大专辑。Davis转向调式爵士，梦幻阵容包括Coltrane、Adderley、Bill Evans。',descriptionEn:'Greatest jazz album ever. Davis embraced modal jazz. Dream lineup: Coltrane, Adderley, Bill Evans.',storiesZh:'几乎所有曲目一次录制完成。Davis只给乐手简单音阶草图。封面只对设计师说：「做点蓝色的。」',storiesEn:'Nearly all tracks single takes. Davis gave only scale sketches. Cover brief: Do something blue.',links:{}});

// ========== APRIL ==========
add('04-05', {id:'nirvana-in-utero-1993',name:'In Utero',nameZh:'母体中',artist:'Nirvana',artistZh:'涅槃',releaseDate:'04-05',year:1993,coverImage:'',genres:['Grunge','Alternative Rock'],language:'english',languageZh:'英语',type:'album',descriptionZh:'涅槃最后录音室专辑，对《Nevermind》成功的反商业回应。Steve Albini粗糙制作，Cobain赤裸歌词。',descriptionEn:'Nirvana final album — anti-commercial response to Nevermind success. Raw Albini production, naked Cobain lyrics.',storiesZh:'Cobain坚持用地下制作人Albini，两周录完，成本不到25000美元。唱片公司听到成品吓坏了。',storiesEn:'Cobain insisted on underground producer Albini. Two weeks, under \$25K. Label was horrified by the result.',links:{}});
add('04-05', {id:'deserts-chang-my-life-2006',name:'My Life Will...',nameZh:'My Life Will...',artist:'Deserts Chang',artistZh:'张悬',releaseDate:'04-05',year:2006,coverImage:'',genres:['Folk','Singer-Songwriter'],language:'chinese',languageZh:'华语',type:'album',descriptionZh:'张悬首专，以木吉他撑起整张唱片。细腻歌词与慵懒真挚唱腔定义台湾新一代独立民谣。',descriptionEn:'Deserts Chang debut built around acoustic guitar. Delicate lyrics and sincere voice defined Taiwan new indie folk.',storiesZh:'出身台湾政商名门却选择完全不同道路。制作费是自己攒的演出酬劳，拒绝家人资助。',storiesEn:'Born into prominent family, chose completely different path. Self-funded with gig savings, refusing family money.',links:{}});
add('04-05', {id:'radiohead-the-bends-1995',name:'The Bends',nameZh:'弯曲',artist:'Radiohead',artistZh:'电台司令',releaseDate:'04-05',year:1995,coverImage:'',genres:['Alternative Rock','Britpop'],language:'english',languageZh:'英语',type:'album',descriptionZh:'Radiohead从《Creep》阴影中走出，展现惊人深度。《Fake Plastic Trees》等证明他们远不止一曲成名。',descriptionEn:'Radiohead emerged from Creep shadow with stunning depth. Proved far more than one-hit wonder.',storiesZh:'Thom Yorke陷入严重创作焦虑，感到被《Creep》定义和囚禁。《Fake Plastic Trees》歌词在看Jeff Buckley演出后一气呵成。',storiesEn:'Yorke suffered creative anxiety, felt imprisoned by Creep. Wrote Fake Plastic Trees after watching Jeff Buckley perform.',links:{}});

add('04-19', {id:'prince-purple-rain-1984',name:'Purple Rain',nameZh:'紫雨',artist:'Prince',artistZh:'王子',releaseDate:'04-19',year:1984,coverImage:'',genres:['Pop','Rock','Funk'],language:'english',languageZh:'英语',type:'album',descriptionZh:'Prince巅峰之作，同名电影原声。连续24周Billboard冠军。《When Doves Cry》等定义80年代声音。',descriptionEn:'Prince peak — film soundtrack. 24 weeks atop Billboard. Defined the 80s sound.',storiesZh:'标题曲1983年慈善演出首次现场录制，长达13分钟。和弦进行借鉴乡村音乐，Prince却把它变成了摇滚歌剧。',storiesEn:'Title track first recorded live at 1983 charity concert — 13 minutes. Chord progression borrowed from country, turned into rock opera.',links:{}});
add('04-19', {id:'jonathan-lee-spirit-1989',name:'生命中的精灵',nameZh:'生命中的精灵',artist:'Jonathan Lee',artistZh:'李宗盛',releaseDate:'04-19',year:1989,coverImage:'',genres:['Folk','Mandopop'],language:'chinese',languageZh:'华语',type:'album',descriptionZh:'李宗盛首专，华语流行最具文学性作品之一。口语化歌词写尽都市中年困顿与温情。',descriptionEn:'Jonathan Lee debut — one of most literary works in Chinese pop. Conversational lyrics capture urban struggles.',storiesZh:'出道前是送瓦斯的工人，歌词里那些写实细节——瓦斯炉、旧沙发、下雨的巷子——都来自这段生活。',storiesEn:'Delivered gas cylinders before music career. Realistic details in songs came from that life.',links:{}});
add('04-19', {id:'the-clash-london-calling-1979',name:'London Calling',nameZh:'伦敦呼叫',artist:'The Clash',artistZh:'冲击乐队',releaseDate:'04-19',year:1979,coverImage:'',genres:['Punk Rock','Reggae'],language:'english',languageZh:'英语',type:'album',descriptionZh:'朋克超越之作。融入雷鬼、爵士、摇滚，将朋克愤怒扩展为广阔政治文化视野。封面砸贝斯照成摇滚史上最著名照片。',descriptionEn:'Punk transcendence. Fused reggae, jazz, rock — expanding punk anger into broad cultural vision.',storiesZh:'封面是贝斯手因不满音响将贝斯砸向地面时抓拍的。他最初觉得「太模糊没法用」——后成滚石史上最佳摇滚照片。',storiesEn:'Cover shot when bassist smashed bass in frustration. He thought it too blurry — became Rolling Stone greatest rock photo.',links:{}});

// ========== MAY ==========
add('05-01', {id:'bob-dylan-highway-61-1965',name:'Highway 61 Revisited',nameZh:'重访61号公路',artist:'Bob Dylan',artistZh:'鲍勃·迪伦',releaseDate:'05-01',year:1965,coverImage:'',genres:['Folk Rock','Blues Rock'],language:'english',languageZh:'英语',type:'album',descriptionZh:'Dylan全面插电标志。《Like a Rolling Stone》六分钟打破流行歌曲长度和主题边界，将摇滚提升为严肃文学。',descriptionEn:'Dylan definitive electric statement. Like a Rolling Stone shattered pop limits at six minutes — elevated rock to serious literature.',storiesZh:'录制是场噩梦——Dylan反复改词，乐队换了一批又一批。年轻吉他手Al Kooper擅自坐到风琴前即兴，Dylan大喊「就是这个！」',storiesEn:'Recording nightmare — Dylan endlessly rewrote, musicians cycled through. Young Al Kooper sat at organ unprompted — Dylan knew instantly.',links:{}});
add('05-01', {id:'zhang-chu-lonely-2017',name:'孤独及其所创造的',nameZh:'孤独及其所创造的',artist:'Zhang Chu',artistZh:'张楚',releaseDate:'05-01',year:2017,coverImage:'',genres:['Folk Rock','Chinese Rock'],language:'chinese',languageZh:'华语',type:'album',descriptionZh:'「魔岩三杰」之一张楚的诗意回归。以观察者视角描绘当代中国城市的孤独与温情。',descriptionEn:'Zhang Chu, one of China Three Rock Heroes, returns with poetic observations of urban Chinese loneliness.',storiesZh:'1994年张楚窦唯何勇红磡演唱会被称为中国摇滚巅峰。二十年后依然保持低调，拒绝商业包装。',storiesEn:'1994 Hong Kong Coliseum concert with Dou Wei and He Yong considered Chinese rock peak. Twenty years later, still low-profile.',links:{}});
add('05-01', {id:'fleetwood-mac-rumours-1977',name:'Rumours',nameZh:'流言',artist:'Fleetwood Mac',artistZh:'弗利特伍德·麦克',releaseDate:'05-01',year:1977,coverImage:'',genres:['Pop Rock','Soft Rock'],language:'english',languageZh:'英语',type:'album',descriptionZh:'在人际关系全面崩溃中诞生的杰作。两对情侣同时分手，每人用写歌互相伤害与疗伤。心碎化为完美流行音乐。',descriptionEn:'Masterpiece born from total interpersonal collapse. Two couples breaking up, writing to hurt and heal. Heartbreak became perfect pop.',storiesZh:'录音棚里到处都是可卡因和眼泪。McVies离婚不再交谈，Buckingham和Nicks公开尖叫争吵。极度痛苦转化为真实张力。',storiesEn:'Studio awash in cocaine and tears. McVies divorced and silent, Buckingham and Nicks screaming. Extreme pain became genuine tension.',links:{}});

add('05-23', {id:'radiohead-ok-computer-1997',name:'OK Computer',nameZh:'好的电脑',artist:'Radiohead',artistZh:'电台司令',releaseDate:'05-23',year:1997,coverImage:'',genres:['Alternative Rock','Art Rock'],language:'english',languageZh:'英语',type:'album',descriptionZh:'关于现代科技焦虑的预言式杰作。在网络泡沫和911之前已敏锐捕捉到即将到来的精神危机。',descriptionEn:'Prophetic masterpiece about modern tech anxiety. Captured coming spiritual crisis before dot-com crash and 9/11.',storiesZh:'Yorke陷入严重抑郁，称这段经历为精神崩溃。乐队在乡间大宅同住数月。某天Yorke沮丧中将麦克风扔进泳池——被采样了。',storiesEn:'Yorke sank into depression, calling it mental breakdown. Band lived together in country mansion. Yorke threw mic into pool — sound was sampled.',links:{}});
add('05-23', {id:'david-tao-black-tangerine-2002',name:'黑色柳丁',nameZh:'黑色柳丁',artist:'David Tao',artistZh:'陶喆',releaseDate:'05-23',year:2002,coverImage:'',genres:['R&B','Mandopop'],language:'chinese',languageZh:'华语',type:'album',descriptionZh:'陶喆第三张专辑，将R&B、摇滚与中国元素融合到新高度。华语R&B成熟期代表作。',descriptionEn:'David Tao third album elevates R&B-rock-Chinese fusion. Landmark of mature Chinese R&B.',storiesZh:'美国长大的ABC回台湾发现华语乐坛几乎全是抒情歌，决心把地道R&B和摇滚制作标准引入华语音乐。',storiesEn:'ABC-raised Tao returned to Taiwan, found Chinese pop dominated by ballads, resolved to bring authentic R&B production standards.',links:{}});
add('05-23', {id:'pixies-doolittle-1989',name:'Doolittle',nameZh:'小杜丽',artist:'Pixies',artistZh:'精灵乐队',releaseDate:'05-23',year:1989,coverImage:'',genres:['Alternative Rock','Indie Rock'],language:'english',languageZh:'英语',type:'album',descriptionZh:'以「安静-响亮-安静」动态对比成另类摇滚蓝图。Cobain多次承认《Smells Like Teen Spirit》就是试图模仿Pixies。',descriptionEn:'Quiet-LOUD-quiet dynamics became alt-rock blueprint. Cobain repeatedly admitted trying to copy Pixies.',storiesZh:'录制期间乐队关系几乎崩溃——主唱和贝斯手不再交谈，贝斯手被禁贡献歌曲，促成了她后来组建The Breeders。',storiesEn:'Band relationships nearly collapsed — singer and bassist stopped speaking. Bassist forbidden from contributing, spurring The Breeders.',links:{}});

// ========== JUNE ==========
add('06-01', {id:'beatles-sgt-pepper-1967',name:'Sgt. Pepper\'s Lonely Hearts Club Band',nameZh:'佩珀军士的孤独之心俱乐部乐队',artist:'The Beatles',artistZh:'披头士',releaseDate:'06-01',year:1967,coverImage:'',genres:['Psychedelic Rock','Art Rock'],language:'english',languageZh:'英语',type:'album',descriptionZh:'流行音乐史上最重要专辑。停止巡演后全情投入录音棚，录制129天700多小时，重新定义流行音乐的可能性。',descriptionEn:'Most important album in pop history. Post-touring, poured everything into studio — 129 days, 700+ hours. Redefined possibilities of pop.',storiesZh:'列侬坚持封面放希特勒被否决。封面集结70多个历史人物纸板剪影，费用是普通封面60倍。结尾和弦是四人同时按下三架钢琴持续40秒。',storiesEn:'Lennon insisted on Hitler — overruled. 70+ historical cutouts cost 60x normal cover. Final chord: four people striking three pianos for 40 seconds.',links:{}});
add('06-01', {id:'zheng-jun-bare-1994',name:'赤裸裸',nameZh:'赤裸裸',artist:'Zheng Jun',artistZh:'郑钧',releaseDate:'06-01',year:1994,coverImage:'',genres:['Rock','Chinese Rock'],language:'chinese',languageZh:'华语',type:'album',descriptionZh:'郑钧首专，融合硬摇滚、民谣与西藏元素。《回到拉萨》《赤裸裸》成经典，销量破百万。',descriptionEn:'Zheng Jun debut blends hard rock, folk, Tibetan elements. Sold over a million, defining Chinese rock golden age.',storiesZh:'录这张专辑时身无分文，住北京朋友家地板。西藏元素来自大学旅行——那片土地的辽阔和纯净成他音乐最独特底色。',storiesEn:'Penniless while recording, sleeping on friend floor in Beijing. Tibetan elements from college trip — land vastness became music distinctive color.',links:{}});
add('06-01', {id:'stevie-wonder-innervisions-1973',name:'Innervisions',nameZh:'内省',artist:'Stevie Wonder',artistZh:'史提夫·汪达',releaseDate:'06-01',year:1973,coverImage:'',genres:['Soul','Funk','R&B'],language:'english',languageZh:'英语',type:'album',descriptionZh:'Stevie Wonder巅峰期代表作，几乎包办所有乐器。《Living for the City》以心碎叙事讲述黑人青年在美国的遭遇。',descriptionEn:'Stevie Wonder peak-era masterpiece, playing nearly all instruments. Living for the City: heartbreaking story of young Black man in America.',storiesZh:'专辑发行三天后遭遇严重车祸昏迷四天。醒来后说：「我闻到了死亡的味道，但选择不跟他走。」',storiesEn:'Three days after release, severe car crash, four-day coma. Waking words: I smelled death, but chose not to go with him.',links:{}});

// ========== JULY ==========
add('07-10', {id:'beastie-boys-licensed-1986',name:'Licensed to Ill',nameZh:'获许可耍酷',artist:'Beastie Boys',artistZh:'野兽男孩',releaseDate:'07-10',year:1986,coverImage:'',genres:['Hip-Hop','Rap Rock'],language:'english',languageZh:'英语',type:'album',descriptionZh:'史上第一张登顶Billboard的嘻哈专辑。Rick Rubin制作，摇滚吉他融合说唱节奏。',descriptionEn:'First hip-hop album to top Billboard. Rick Rubin production fusing rock guitars with rap beats.',storiesZh:'Beastie Boys最初是硬核朋克乐队，做嘻哈纯因好玩。《Fight For Your Right》本是讽刺派对男孩文化——很多人当真了。',storiesEn:'Started as hardcore punk band, switched to hip-hop for fun. Fight For Your Right was satire — many took it literally.',links:{}});
add('07-10', {id:'jay-chou-fantasy-plus-2001',name:'范特西Plus',nameZh:'范特西Plus',artist:'Jay Chou',artistZh:'周杰伦',releaseDate:'07-10',year:2001,coverImage:'',genres:['Mandopop','R&B'],language:'chinese',languageZh:'华语',type:'album',descriptionZh:'周杰伦R&B、嘻哈、古典与中国风融合完全成熟。从录音室助理到重塑华语流行，传奇崛起。',descriptionEn:'Jay Chou fusion of R&B, hip-hop, classical, Chinese elements reached maturity. From studio assistant to reshaping Chinese pop.',storiesZh:'两年前还是睡在录音室地板的小助理。两年后终结了华语乐坛翻唱日韩歌曲的模式，开启原创为主的新纪元。',storiesEn:'Two years earlier: studio assistant sleeping on floor. Two years later: ended Chinese pop tradition of covering J-pop/K-pop.',links:{}});
add('07-10', {id:'bjork-post-1995',name:'Post',nameZh:'邮递',artist:'Björk',artistZh:'比约克',releaseDate:'07-10',year:1995,coverImage:'',genres:['Art Pop','Electronic','Trip Hop'],language:'english',languageZh:'英语',type:'album',descriptionZh:'从狂暴《Army of Me》到华丽《It\'s Oh So Quiet》，每首歌都是一个独立世界。封面红色夹克成90年代最标志性视觉之一。',descriptionEn:'From ferocious Army of Me to gorgeous It\'s Oh So Quiet, each track is its own universe. Red jacket: most iconic 90s visual.',storiesZh:'录制期间经历邮包炸弹事件——迷恋她的粉丝寄来的。让Björk重新思考名人与粉丝的边界。',storiesEn:'During recording, experienced mail-bomb incident from obsessed fan. Made her rethink celebrity-fan boundary.',links:{}});

// ========== AUGUST ==========
add('08-15', {id:'beatles-help-1965',name:'Help!',nameZh:'救命！',artist:'The Beatles',artistZh:'披头士',releaseDate:'08-15',year:1965,coverImage:'',genres:['Pop Rock','Folk Rock'],language:'english',languageZh:'英语',type:'album',descriptionZh:'披头士第五张专辑，同名电影原声。标题曲是Lennon在名声重压下发出的求救信号。含史上被翻唱最多的《Yesterday》。',descriptionEn:'Beatles fifth album, film soundtrack. Title track was Lennon genuine cry for help. Contains Yesterday — most covered song in history.',storiesZh:'《Yesterday》旋律是McCartney在梦中听到的。醒来冲到钢琴前，之后好几个月以为无意识抄袭了别人的歌。',storiesEn:'Yesterday melody came to McCartney in dream. Spent months convinced he unconsciously plagiarized.',links:{}});
add('08-15', {id:'hush-chance-fate-2015',name:'机会与命运',nameZh:'机会与命运',artist:'Hush!',artistZh:'Hush!',releaseDate:'08-15',year:2015,coverImage:'',genres:['Indie Pop','Mandopop'],language:'chinese',languageZh:'华语',type:'album',descriptionZh:'台湾独立流行乐队Hush!代表作。主唱以天文学隐喻都市情感，创造独特的「宇宙系」表达。孙燕姿《克卜勒》即由其填词。',descriptionEn:'Taiwanese indie pop band representative work. Frontman uses astronomy metaphors for urban emotions — unique cosmic expression.',storiesZh:'Hush最早在台北Live House驻唱，因喜欢融入星座隐喻被歌迷称为「宇宙系歌手」。',storiesEn:'Hush started in Taipei Live Houses, nicknamed cosmic singer for astronomical metaphors.',links:{}});
add('08-15', {id:'green-day-dookie-1994',name:'Dookie',nameZh:'屎',artist:'Green Day',artistZh:'绿日',releaseDate:'08-15',year:1994,coverImage:'',genres:['Punk Rock','Pop Punk'],language:'english',languageZh:'英语',type:'album',descriptionZh:'90年代朋克复兴推向主流。《Basket Case》将焦虑包装在精确三分钟朋克结构中。全球销量2000万张。',descriptionEn:'Pushed 90s punk revival mainstream. Basket Case wrapped anxiety in precise 3-minute punk. 20 million sold worldwide.',storiesZh:'《Basket Case》写于Billie Joe一次恐慌发作后。他以为自己疯了去看心理医生——只是焦虑症。坐在路边20分钟写完。',storiesEn:'Basket Case written after Billie Joe panic attack. Convinced going crazy, saw psychiatrist — just anxiety. Wrote on curb in 20 minutes.',links:{}});

// ========== SEPTEMBER ==========
add('09-24', {id:'nirvana-nevermind-1991',name:'Nevermind',nameZh:'别介意',artist:'Nirvana',artistZh:'涅槃',releaseDate:'09-24',year:1991,coverImage:'',genres:['Grunge','Alternative Rock'],language:'english',languageZh:'英语',type:'album',descriptionZh:'改变90年代音乐格局。《Smells Like Teen Spirit》一声怒吼终结华丽金属时代。封面追美钞的婴儿成经典标志。',descriptionEn:'Changed 90s music. One roar ended hair metal era. Cover: baby swimming toward dollar bill — iconic symbol.',storiesZh:'录制预算仅65000美元。Cobain嫌混音太干净请来Andy Wallace——然后又嫌Wallace太干净。取代Michael Jackson登顶Billboard。',storiesEn:'Budget: \$65K. Cobain found mix too raw, brought in Wallace — then complained it was too clean. Dethroned Michael Jackson atop charts.',links:{}});
add('09-24', {id:'xu-wei-elsewhere-1997',name:'在别处',nameZh:'在别处',artist:'Xu Wei',artistZh:'许巍',releaseDate:'09-24',year:1997,coverImage:'',genres:['Rock','Chinese Rock'],language:'chinese',languageZh:'华语',type:'album',descriptionZh:'许巍首专，中国摇滚最动人作品之一。不同于同时代的愤怒，流淌着深沉忧伤与对远方的向往。',descriptionEn:'Xu Wei debut, one of Chinese rock most moving works. Unlike contemporaries anger, flows with deep melancholy.',storiesZh:'西安部队大院长大，后成北京标准北漂。专辑中的漂泊感来自真实生活。多年后《蓝莲花》成中国自驾游圈子国歌。',storiesEn:'Grew up in military compound, became Beijing drifter. Years later Blue Lotus became road trip anthem.',links:{}});
add('09-24', {id:'beach-boys-pet-sounds-1966',name:'Pet Sounds',nameZh:'宠物之声',artist:'The Beach Boys',artistZh:'沙滩男孩',releaseDate:'09-24',year:1966,coverImage:'',genres:['Baroque Pop','Psychedelic Pop'],language:'english',languageZh:'英语',type:'album',descriptionZh:'Brian Wilson杰作，流行音乐最精美制作之一。用管弦乐、特雷门琴等把流行音乐当交响乐编排。直接启发《Sgt. Pepper》。',descriptionEn:'Brian Wilson masterpiece — one of pop most exquisite productions. Orchestra, theremin as symphony. Directly inspired Sgt. Pepper.',storiesZh:'Wilson在精神崩溃和药物滥用状态下录制。McCartney后来说：「没有《Pet Sounds》就不会有《Sgt. Pepper》。」',storiesEn:'Wilson recorded amid breakdown and substance abuse. McCartney: Without Pet Sounds, no Sgt. Pepper.',links:{}});

// ========== OCTOBER ==========
add('10-01', {id:'pink-floyd-wish-you-1975',name:'Wish You Were Here',nameZh:'愿你在此',artist:'Pink Floyd',artistZh:'平克·弗洛伊德',releaseDate:'10-01',year:1975,coverImage:'',genres:['Progressive Rock'],language:'english',languageZh:'英语',type:'album',descriptionZh:'Pink Floyd献给前成员Syd Barrett的情书。全专围绕缺席展开，批判音乐产业，怀念逝去友人。',descriptionEn:'Pink Floyd love letter to former member Syd Barrett. Album revolves around absence — music industry critique, mourning for lost friend.',storiesZh:'录制时一个剃光头的陌生胖男人走进录音棚——竟是Syd Barrett本人，被毒品和精神疾病彻底摧毁。这是他最后一次出现在乐队面前。',storiesEn:'During recording, strange bald overweight man walked in — it was Syd Barrett, destroyed by drugs and mental illness. His last appearance before the band.',links:{}});
add('10-01', {id:'tanya-chua-amphibian-2005',name:'双栖动物',nameZh:'双栖动物',artist:'Tanya Chua',artistZh:'蔡健雅',releaseDate:'10-01',year:2005,coverImage:'',genres:['Mandopop','Singer-Songwriter'],language:'chinese',languageZh:'华语',type:'album',descriptionZh:'新加坡唱作人蔡健雅代表作，四度金曲奖最佳国语女歌手。慵懒而富质感的嗓音配合精致都市情歌编曲。',descriptionEn:'Singaporean Tanya Chua — record four-time Golden Melody Best Female Singer. Languid textured voice with sophisticated urban arrangements.',storiesZh:'中文是后来才学的，却能写出比很多母语者更精妙的歌词。被称为「金曲奖收割机」。',storiesEn:'Mandarin learned later in life, yet writes more nuanced lyrics than many native speakers. Called Golden Melody Award Harvester.',links:{}});
add('10-01', {id:'tony-bennett-unplugged-1994',name:'MTV Unplugged',nameZh:'MTV不插电',artist:'Tony Bennett',artistZh:'托尼·班奈特',releaseDate:'10-01',year:1994,coverImage:'',genres:['Jazz','Vocal Jazz'],language:'english',languageZh:'英语',type:'album',descriptionZh:'68岁Tony Bennett在MTV舞台向年轻一代介绍Great American Songbook。获格莱美年度专辑。',descriptionEn:'68-year-old Bennett introduced Great American Songbook to new generation on MTV. Won Grammy Album of Year.',storiesZh:'唱片公司最初强烈反对——68岁传统歌手去MTV做不插电？但当他站上舞台，台下年轻观众全部安静了。',storiesEn:'Label dead against — 68-year-old traditional singer on MTV? But when he stood on stage, young crowd fell silent.',links:{}});

add('10-11', {id:'bob-marley-exodus-1977',name:'Exodus',nameZh:'出埃及记',artist:'Bob Marley',artistZh:'鲍勃·马利',releaseDate:'10-11',year:1977,coverImage:'',genres:['Reggae'],language:'english',languageZh:'英语',type:'album',descriptionZh:'暗杀未遂后在伦敦流亡中录制。《Jamming》《One Love》成雷鬼最广为传唱的圣歌。《时代》「世纪最佳专辑」。',descriptionEn:'Recorded in London exile after assassination attempt. TIME Album of the Century.',storiesZh:'1976年枪手闯入牙买加家中向他与妻子开枪。奇迹幸存，第二天仍带伤登台。',storiesEn:'1976: gunmen stormed Jamaican home, shot him and wife. Survived, performed next day still bandaged.',links:{}});
add('10-11', {id:'joker-xue-actor-2017',name:'演员',nameZh:'演员',artist:'Joker Xue',artistZh:'薛之谦',releaseDate:'10-11',year:2017,coverImage:'',genres:['Mandopop','Ballad'],language:'chinese',languageZh:'华语',type:'single',descriptionZh:'近年华语播放量最高单曲之一。以近乎残忍的坦诚描绘爱情中的欺骗与自我欺骗。',descriptionEn:'One of recent years most-streamed Chinese singles. Near-brutal honesty about deception and self-deception in love.',storiesZh:'出道后沉寂十年，靠开火锅店和写段子维生。当所有人以为他只是搞笑网红时以这首歌强势回归。',storiesEn:'Faded for decade after debut, survived by running hotpot restaurant. Just as everyone thought he was just a comedian — returned triumphantly.',links:{}});
add('10-11', {id:'u2-joshua-tree-1987',name:'The Joshua Tree',nameZh:'约书亚树',artist:'U2',artistZh:'U2',releaseDate:'10-11',year:1987,coverImage:'',genres:['Rock','Alternative Rock'],language:'english',languageZh:'英语',type:'album',descriptionZh:'U2从体育馆乐队跃升全球现象。深受美国广阔地貌和根源音乐影响，The Edge延迟吉他创造标志性大空间声响。',descriptionEn:'U2 vaulted from arena band to global phenomenon. The Edge delay guitar created signature big space sound.',storiesZh:'灵感来自1986年美国西南沙漠旅行。封面在约书亚树国家公园拍摄——Bono在刺骨寒风中穿着单薄皮夹克。',storiesEn:'Inspired by 1986 Southwest desert travels. Cover shot in Joshua Tree National Park — Bono in thin leather jacket against biting wind.',links:{}});

// ========== NOVEMBER ==========
add('11-08', {id:'doors-debut-1967',name:'The Doors',nameZh:'大门',artist:'The Doors',artistZh:'大门乐队',releaseDate:'11-08',year:1967,coverImage:'',genres:['Psychedelic Rock'],language:'english',languageZh:'英语',type:'album',descriptionZh:'The Doors首专，Jim Morrison诗人气质与Ray Manzarek风琴定义暗黑迷幻摇滚。《Light My Fire》7分钟即兴打破流行格式。',descriptionEn:'The Doors debut defined dark psychedelic rock. Light My Fire 7-minute improvisation broke pop format.',storiesZh:'《The End》在Whisky演出时加入俄狄浦斯即兴段落被当场解雇——但正是这场演出吸引了唱片公司。',storiesEn:'The End Oedipal improvisation at Whisky got them fired — but that performance caught label attention.',links:{}});
add('11-08', {id:'na-ying-conquer-1998',name:'征服',nameZh:'征服',artist:'Na Ying',artistZh:'那英',releaseDate:'11-08',year:1998,coverImage:'',genres:['Mandopop','Ballad'],language:'chinese',languageZh:'华语',type:'album',descriptionZh:'那英代表作，华语情歌黄金时代巅峰。标题曲以近乎咆哮的情感爆发展现独特嗓音张力，销量破百万。',descriptionEn:'Na Ying masterpiece — peak of Chinese ballad golden age. Near-roaring emotional intensity, million-plus sales.',storiesZh:'从东北沈阳考到北京，从谷建芬学生成长为华语天后。粗粝中带着细腻的嗓音被视为最独特音色之一。',storiesEn:'From Shenyang to Beijing, from student to diva. Rough yet delicate voice considered one of most unique timbres.',links:{}});
add('11-08', {id:'joy-division-unknown-1979',name:'Unknown Pleasures',nameZh:'未知的愉悦',artist:'Joy Division',artistZh:'欢乐分队',releaseDate:'11-08',year:1979,coverImage:'',genres:['Post-Punk'],language:'english',languageZh:'英语',type:'album',descriptionZh:'后朋克定义性作品。Ian Curtis低沉男中音在冰冷鼓机间游走，创造前所未有的都市孤绝氛围。封面脉冲星波形成最著名设计之一。',descriptionEn:'Post-punk defining work. Cover: pulsar waveform — most famous design. Curtis lyrics filled with epilepsy and depression metaphors.',storiesZh:'封面是第一个被发现的脉冲星CP 1919无线电信号图。专辑发行仅六个月后Curtis在家中自杀，年仅23岁。',storiesEn:'Cover: radio signal of pulsar CP 1919. Six months after release, Curtis hanged himself at 23. Album became a suicide note — and eternal classic.',links:{}});

add('11-22', {id:'beatles-white-1968',name:'The Beatles (White Album)',nameZh:'白色专辑',artist:'The Beatles',artistZh:'披头士',releaseDate:'11-22',year:1968,coverImage:'',genres:['Rock','Pop','Experimental'],language:'english',languageZh:'英语',type:'album',descriptionZh:'披头士唯一双专辑，最分裂也最丰富。30首歌涵盖几乎所有音乐类型。纯白封面是极简主义艺术家设计。',descriptionEn:'Beatles only double album — most fragmented yet diverse. White cover: minimalist Richard Hamilton design.',storiesZh:'录制期间关系极度紧张。Ringo一度退出，Paul因Lennon带Yoko进棚大发雷霆。混乱中造就无数经典。',storiesEn:'Band relations hit breaking point. Ringo briefly quit, Paul raged about Yoko. Chaos produced countless classics.',links:{}});
add('11-22', {id:'silence-wang-slowly-2014',name:'慢慢懂',nameZh:'慢慢懂',artist:'Silence Wang',artistZh:'汪苏泷',releaseDate:'11-22',year:2014,coverImage:'',genres:['Mandopop','R&B'],language:'chinese',languageZh:'华语',type:'album',descriptionZh:'汪苏泷从网络歌手到主流艺人转型之作。「QQ音乐三巨头」代表中国互联网草根音乐力量崛起。',descriptionEn:'Silence Wang transition from internet singer to mainstream. QQ Music Big Three: rise of Chinese grassroots internet music.',storiesZh:'三巨头现象——三个无签约年轻人在家自制歌曲积累上亿播放，绕过传统唱片工业守门人。',storiesEn:'Big Three: three unsigned youngsters recording at home, hundreds of millions of plays, bypassing industry gatekeepers.',links:{}});
add('11-22', {id:'sinatra-wee-small-1955',name:'In the Wee Small Hours',nameZh:'在凌晨时分',artist:'Frank Sinatra',artistZh:'弗兰克·辛纳屈',releaseDate:'11-22',year:1955,coverImage:'',genres:['Vocal Jazz','Traditional Pop'],language:'english',languageZh:'英语',type:'album',descriptionZh:'音乐史最早概念专辑之一。全部16首歌围绕失眠与心碎。为披头士、Pink Floyd等提供最早范本。',descriptionEn:'One of first concept albums. All 16 songs about insomnia and heartbreak. Template for Beatles, Pink Floyd.',storiesZh:'录制时辛纳屈深陷与Ava Gardner婚变痛苦，曾在录音时崩溃大哭。封面：深夜空无一人街头蓝色路灯下孤独身影。',storiesEn:'Sinatra in agony over crumbling marriage, broke down crying mid-session. Cover: lonely figure under blue lamplight on empty street.',links:{}});

// ========== DECEMBER ==========
add('12-25', {id:'coltrane-love-supreme-1964',name:'A Love Supreme',nameZh:'至高无上的爱',artist:'John Coltrane',artistZh:'约翰·柯川',releaseDate:'12-25',year:1964,coverImage:'',genres:['Jazz','Modal Jazz','Spiritual Jazz'],language:'other',languageZh:'纯音乐',type:'album',descriptionZh:'Coltrane精神自传，四乐章组曲记录与毒瘾的斗争和信仰中的救赎。圣诞夜录制，对他不是表演而是礼拜。',descriptionEn:'Coltrane spiritual autobiography. Four movements — addiction struggle and redemption through faith. Recorded Christmas Eve.',storiesZh:'1957年因海洛因成瘾被Miles Davis开除。把自己关在房间戒掉毒瘾，发誓余生赞美上帝。七年后圣诞夜凝聚重生经历。',storiesEn:'1957: fired by Miles Davis for heroin addiction. Locked himself in room, kicked habit, vowed to praise God. Seven years later distilled rebirth.',links:{}});
add('12-25', {id:'teresa-teng-dan-dan-1983',name:'淡淡幽情',nameZh:'淡淡幽情',artist:'Teresa Teng',artistZh:'邓丽君',releaseDate:'12-25',year:1983,coverImage:'',genres:['Mandopop','Chinese Classical'],language:'chinese',languageZh:'华语',type:'album',descriptionZh:'邓丽君最具文化厚度专辑。12首歌歌词皆取自唐宋诗词名篇。在两岸对峙年代成为跨越政治隔阂的文化纽带。',descriptionEn:'Teresa Teng most culturally significant album. All 12 songs set Tang/Song poems to new music. Cultural bridge across political divide.',storiesZh:'《但愿人长久》至今是中秋节华人世界播放最多的歌曲。她的歌声成为两岸共同的文化珍宝。',storiesEn:'Wishing We Last Forever remains most-played Mid-Autumn Festival song worldwide. Her voice became shared cultural treasure.',links:{}});
add('12-25', {id:'paul-simon-graceland-1986',name:'Graceland',nameZh:'恩赐之地',artist:'Paul Simon',artistZh:'保罗·西蒙',releaseDate:'12-25',year:1986,coverImage:'',genres:['Folk Rock','World Music'],language:'english',languageZh:'英语',type:'album',descriptionZh:'Simon最具冒险精神专辑。前往种族隔离南非与黑人音乐家合作，将美国民谣与非洲乡镇音乐融合。1987格莱美年度专辑。',descriptionEn:'Simon most adventurous album. Traveled to apartheid South Africa, collaborated with Black musicians. 1987 Grammy Album of Year.',storiesZh:'去南非录音在当时引发巨大争议——联合国对种族隔离实施文化抵制。Simon坚持音乐合作应打破隔阂。',storiesEn:'South Africa trip hugely controversial — UN cultural boycott. Simon insisted collaboration should break barriers.',links:{}});

// Save sorted
const sorted = {};
Object.keys(db).sort().forEach(k => { sorted[k] = db[k]; });
sorted._meta = {
  generated: new Date().toISOString(),
  version: 5,
  totalDays: Object.keys(db).length,
  note: 'Strictly accurate release dates. Items can be albums or singles. Max 3 per day. Each day has exactly 1 Chinese entry where possible.'
};

fs.writeFileSync('data/albums.json', JSON.stringify(sorted, null, 2));

let totalItems = 0;
Object.keys(db).forEach(k => { totalItems += db[k].items.length; });
console.log('Days:', Object.keys(db).length, '| Items:', totalItems);
console.log('Dates:', Object.keys(db).join(', '));
